install:
  - cinst fake -pre
build_script:
#  - ps: Fake.exe -v run build.fsx
  - ps: .\build.cmd
on_failure:
  - appveyor PushArtifact FAKE.svclog
test: off
artifacts:
  - path: 'nuget\dotnetcore\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\legacy\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\dotnetcore\Fake.netcore\*.zip'
    type: Zip