version: 2

jobs:
  build:
    working_directory: /build
    docker:
      - image: mono:5.8.0.127
    steps:
      - checkout
      - run:
          name: install-fake
          command: |
            apt-get update
            apt-get install -y libunwind8 libicu52 unzip wget git
            wget https://github.com/fsharp/FAKE/releases/download/5.0.0-beta024/fake-dotnetcore-ubuntu.14.04-x64.zip -O /tmp/fake-dotnetcore-ubuntu.14.04-x64.zip
            mkdir fake-dotnetcore
            unzip /tmp/fake-dotnetcore-ubuntu.14.04-x64.zip -d fake-dotnetcore || echo unzip returned $?
            chmod +x $PWD/fake-dotnetcore/fake
      - run:
          name: build-project
          command: |
            export TERM=xterm-256color
            export PATH=$PATH:$PWD/fake-dotnetcore/
            fake run build.fsx