name: FAKE Release

# this workflow will build the project, run tests for final check, generate artifacts for a release, and release

on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: 'Release Version'
                required: true
                default: '1.0.0-1'

jobs:
    release:
        runs-on: windows-latest
        environment: Production
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET 6
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '6.0.301'
            - name: Restore dotnet tools
              run: dotnet tool restore
            - name: remove current fake runner tool
              run: dotnet tool uninstall fake-cli
            - name: Build fake runner
              run: dotnet pack -p:PackageVersion=${{ github.event.inputs.releaseVersion }} src/app/fake-cli/fake-cli.fsproj
            - name: add fake runner as a tool
              run: dotnet tool install fake-cli --add-source "./src/app/fake-cli/bin/Debug" --version ${{ github.event.inputs.releaseVersion }}
            - name: Build
              run: dotnet fake build -t Release_BuildAndTest --parallel 3
            - name: publish build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: fake-artifacts
                  path: release/artifacts
            - name: Release
              env:
                  ARTIFACTS_DIRECTORY: "${{github.workspace}}/release/artifacts"
                  CHOCO_SOURCE: ${{ secrets.CHOCO_SOURCE }}
                  FAKE_DETAILED_ERRORS: true
                  GIT_DIRECTORY: ${{github.workspace}}
                  CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
                  DOCS_DOMAIN: ${{ secrets.DOCS_DOMAIN }}
                  IGNORE_CONFLICT: true
                  NUGET_KEY: ${{ secrets.NUGET_KEY }}
                  NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
                  RELEASE_USER_GITHUB: ${{ secrets.RELEASE_USER_GITHUB }}
                  REPOSITORY_NAME_GITHUB: ${{ secrets.REPOSITORY_NAME_GITHUB }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: ${{github.workspace}}/release/dotnetcore/Fake.netcore/win-x64/fake.exe build -t FastRelease
