name: FAKE Release

# this workflow will build the project, run tests for final check, generate artifacts for a release, and release

on:
    push:
        branches: [ release/next ]

jobs:
    release:
        runs-on: windows-latest
        environment: Production
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NETCORE 3.1
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '3.1.x'
            - name: Setup .NET 6
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '6.0.100-preview.3.21202.5'
            - uses: actions/cache@v2
              with:
                  path: ~/.nuget/packages
                  key: windows-latest-nuget-${{ hashFiles('**/paket.lock') }}
                  restore-keys: |
                      windows-latest-nuget
            - name: Restore dotnet tools
              run: dotnet tool restore
            - name: remove current fake runner tool
              run: dotnet tool uninstall fake-cli
            - name: Build fake runner
              run: dotnet pack --version-suffix 1 src/app/fake-cli/fake-cli.fsproj
            - name: add fake runner as a tool
              run: dotnet tool install fake-cli --add-source "./src/app/fake-cli/bin/Debug" --version 1.0.0-1
            - name: Build
              run: dotnet fake build -t Release_BuildAndTest --parallel 3
            - name: publish build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: fake-artifacts
                  path: release/artifacts
            - name: Release
              env:
                  ARTIFACTS_DIRECTORY: "${{github.workspace}}/release/artifacts"
                  CHOCO_SOURCE: "disabled"
                  FAKE_DETAILED_ERRORS: true
                  GIT_DIRECTORY: ${{github.workspace}}
                  CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
                  DOCS_DOMAIN: ${{ secrets.DOCS_DOMAIN }}
                  NUGET_KEY: ${{ secrets.NUGET_KEY }}
                  NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
                  RELEASE_USER_GITHUB: ${{ secrets.RELEASE_USER_GITHUB }}
                  REPOSITORY_NAME_GITHUB: ${{ secrets.REPOSITORY_NAME_GITHUB }}
                  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
              run: ${{github.workspace}}/release/dotnetcore/Fake.netcore/win7-x64/fake.exe build -t FastRelease
